version: 2

executors:
  setup:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/martinjai.me


jobs:
  build:
    executor: setup
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    executor: setup
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn
      - run: yarn test

  deploy:
    executor: setup

    steps:
      - checkout
      - run:
          name: Set up github credentials
          command: bash ./.circleci/set-gh-creds.sh
      - run: yarn
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
